// Seed data — used as fallback when Sanity is not yet configured
// Once Sanity is set up, this data is replaced by CMS content

export const SEED_PRODUCTS = [
  {
    _id: 'seed-1',
    nameHi: 'चटनी दोना',
    nameEn: 'Chutney Dona',
    size: '4"',
    pack: '100 pcs',
    variants: ['Color', 'Silver'],
    bestFor: 'Chutney, pickle, dip',
    image: null,
    priceColor: 10,
    priceSilver: 15,
  },
  {
    _id: 'seed-2',
    nameHi: 'बताशा दोना',
    nameEn: 'Batasha Dona',
    size: '5.5"',
    pack: '100 pcs',
    variants: ['Color', 'Silver'],
    bestFor: 'Batasha, mithai, prasad, puja',
    image: null,
    priceColor: 18,
    priceSilver: 22,
  },
  {
    _id: 'seed-3',
    nameHi: 'समोसा दोना',
    nameEn: 'Samosa Dona',
    size: '6"',
    pack: '100 pcs',
    variants: ['Color', 'Silver'],
    bestFor: 'Samosa, kachori, snacks',
    image: '/dona-100pcs.png',
    priceColor: 23,
    priceSilver: 28,
  },
  {
    _id: 'seed-4',
    nameHi: 'समोसा प्लेट',
    nameEn: 'Samosa Plate',
    size: '6"',
    pack: '50 pcs',
    variants: ['Silver'],
    bestFor: 'Flat serving, events',
    image: null,
    priceColor: null,
    priceSilver: 28,
  },
  {
    _id: 'seed-5',
    nameHi: 'कटोरा दोना',
    nameEn: 'Katora Dona',
    size: '7"',
    pack: '50 pcs',
    variants: ['Color', 'Silver'],
    bestFor: 'Dal, sabzi, curry',
    image: null,
    priceColor: 20,
    priceSilver: 23,
  },
  {
    _id: 'seed-6',
    nameHi: 'कटोरा प्लेट',
    nameEn: 'Katora Plate',
    size: '7"',
    pack: '50 pcs',
    variants: ['Silver'],
    bestFor: 'Full serving, events',
    image: null,
    priceColor: null,
    priceSilver: 23,
  },
  {
    _id: 'seed-7',
    nameHi: 'बड़ा कटोरा',
    nameEn: 'Bada Katora',
    size: '8"',
    pack: '50 pcs',
    variants: ['Color', 'Silver'],
    bestFor: 'Langar, bhandara, full meal',
    image: null,
    priceColor: 23,
    priceSilver: 27,
  },
  {
    _id: 'seed-8',
    nameHi: 'बड़ी प्लेट',
    nameEn: 'Bada Plate',
    size: '8"',
    pack: '50 pcs',
    variants: ['Silver'],
    bestFor: 'Wedding bhoj, temple events',
    image: null,
    priceColor: null,
    priceSilver: 27,
  },
  {
    _id: 'seed-9',
    nameHi: 'सिल्वर थाली',
    nameEn: 'Silver Thali',
    size: '12"',
    pack: '25 pcs',
    variants: ['Silver'],
    bestFor: 'Festive meals, catering, buffet, full dinner',
    image: '/silver-thali.png',
    priceColor: null,
    priceSilver: 35,
  },
]

export const SEED_SETTINGS = {
  heroTagline: 'मतलब भरोसा।',
  heroPromise: '100 माने पूरे 100 — गिन के देखो।',
  heroBrandLine: 'Jo likha hai — woh hi milega।',
  storyText: null,
  whatsappNumber: '919839436346',
  phone: '9839436346',
  email: 'care@bajrangi.eshanura.com',
  address: '908, Hathipur-Uttari, Lakhimpur-Kheri (U.P.) 262701, India',
}
